# -*- coding: utf-8 -*-
"""Day_16_14March.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WW0rVlPBna0Qyhcxvec5qTUPC5yS-9F1
"""

# Scenario: Fitness & Wellness Chatbot Training
# You feed it these sentences:
# - “Push-ups strengthen chest and triceps”
# - “Yoga improves flexibility and balance”
# - “Apples are rich in fiber”
# - “Cardio exercises boost heart health”
# 👉 In this case, the chatbot learns to distinguish between exercise facts, nutrition facts, and general wellness statements, so it can tailor its responses — e.g., suggesting workouts, offering diet tips, or explaining health benefits.
# Would you like me to design a third scenario (maybe in education or travel) so you have a set of examples across different industries?

# Import libraries
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Training data
sentences = [
    "Push-ups strengthen chest and triceps",
    "Yoga improves flexibility and balance",
    "Apples are rich in fiber",
    "Cardio exercises boost heart health",
    "Bananas provide potassium",
    "Running improves stamina"
]

labels = [
    "exercise",
    "exercise",
    "nutrition",
    "exercise",
    "nutrition",
    "exercise"
]

# Convert text into numerical vectors
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

# Train classifier
model = LogisticRegression()
model.fit(X, labels)

# Chatbot function
def wellness_chatbot(user_input):
    vec = vectorizer.transform([user_input])
    prediction = model.predict(vec)[0]

    if prediction == "exercise":
        return "💪 This looks like an exercise topic. I can suggest workouts!"
    elif prediction == "nutrition":
        return "🥗 This is about nutrition. I can provide diet tips!"
    else:
        return "🌿 This relates to general wellness."

# Test chatbot
while True:
    user = input("Ask something about fitness: ")
    if user.lower() == "exit":
        break

    response = wellness_chatbot(user)
    print("Bot:", response)

# Scenario: Healthcare Chatbot – Patient Symptom Matching
# Imagine you’re designing a healthcare chatbot that helps patients find possible conditions based on their symptoms. Both patients and conditions are represented as vectors of features (e.g., fever, cough, fatigue, headache).
# - Patient’s symptom vector:
# [0.2,0.8,-0.3,0.5] → mild fever, strong cough, no fatigue, moderate headache.
# - Condition’s symptom profile vector:
# [0.1,0.9,-0.2,0.4] → mild fever, strong cough, little fatigue, moderate headache.
# The chatbot uses cosine similarity to measure how closely the patient’s symptoms align with the condition’s profile

import numpy as np

# Patient symptom vector
patient = np.array([0.2, 0.8, -0.3, 0.5])

# Condition symptom vector
condition = np.array([0.1, 0.9, -0.2, 0.4])

# Dot product
dot_product = np.dot(patient, condition)

# Magnitudes
norm_patient = np.linalg.norm(patient)
norm_condition = np.linalg.norm(condition)

# Cosine similarity
cosine_similarity = dot_product / (norm_patient * norm_condition)

print("Cosine Similarity:", cosine_similarity)

# Scenario: Warehouse Robot Navigation
# Imagine a warehouse where a robot needs to pick up items.
# - The robot is currently at position (1,2) on the warehouse grid.
# - The item it needs to collect is stored at position (4,6).
# The robot’s navigation system calculates the straight-line distance to the item so it knows how far it must travel if it moves directly.

import math

# Robot position
x1, y1 = 1, 2

# Item position
x2, y2 = 4, 6

# Distance formula
distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print("Straight-line distance:", distance)

# Scenario: Basketball Player Evaluation
# A coach is evaluating how well a player’s skills match the team’s current needs.
# - The team’s requirement vector is a = [2,5,1].
# - 2 = need for shooting ability
# - 5 = need for defense
# - 1 = need for passing
# - The player’s skill vector is b = [3,4,2].
# - 3 = player’s shooting ability
# - 4 = defensive ability
# - 2 = passing ability
# The coach calculates the dot product:

import numpy as np

# Team requirement vector
a = np.array([2, 5, 1])

# Player skill vector
b = np.array([3, 4, 2])

# Dot product
result = np.dot(a, b)

print("Dot Product:", result)

# # 🛒 Scenario: E‑Commerce Product Recommendations
# # Imagine you’re building a smart recommendation engine for an online store.
# # - Problem: Customers often search with phrases like “comfortable running shoes”,
#  but the catalog has items
# #  titled “lightweight sneakers for jogging”. Traditional keyword
#  search struggles to connect these.
# # - Solution: Use embeddings to capture semantic meaning of product
# descriptions and customer queries.

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# 🛒 Customer query embedding (semantic meaning of "comfortable running shoes")
query_embedding = np.array([0.1, 0.8, 0.5])

# 📦 Product catalog embeddings (semantic meaning of product descriptions)
product_embeddings = {
    "lightweight sneakers for jogging": np.array([0.2, 0.7, 0.6]),
    "formal leather shoes": np.array([0.9, 0.1, 0.2]),
    "sandals for summer": np.array([0.3, 0.4, 0.5])
}

# 🔍 Compute similarity between query and each product
for product, embedding in product_embeddings.items():
    similarity = np.dot(query_embedding, embedding)  # fast similarity check
    cosine_sim = cosine_similarity([query_embedding], [embedding])[0][0]  # normalized similarity
    print(f"{product} → Dot Product: {similarity:.3f}, Cosine Similarity: {cosine_sim:.3f}")

# ✅ Recommendation: pick the product with highest similarity
best_match = max(product_embeddings.items(), key=lambda x: np.dot(query_embedding, x[1]))
print("\nRecommended Product:", best_match[0])

# 🎓 Scenario: Online Learning Platform Recommendations
#Imagine you’re building a smart recommendation engine for an online education platform.
#- Problem: Students often search with phrases like “beginner-friendly Python tutorials”, but the course catalog has items titled “Introduction to Programming with Python”. Traditional keyword search struggles to connect these because the words don’t match exactly.
#- Solution: Use embeddings to capture the semantic meaning of both student queries and course descriptions. By comparing embeddings with dot product or cosine similarity, the system can recommend the most relevant courses even when the wording is different

# Install required libraries
!pip install sentence-transformers scikit-learn

# Import libraries
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Course catalog
courses = [
    "Introduction to Programming with Python",
    "Advanced Data Science with Python",
    "Web Development using HTML, CSS, and JavaScript",
    "Machine Learning Fundamentals",
    "Python for Data Analysis",
    "Deep Learning with Neural Networks"
]

# Convert course titles into embeddings
course_embeddings = model.encode(courses)

# Student search query
query = "beginner-friendly Python tutorials"

# Convert query into embedding
query_embedding = model.encode([query])

# Compute cosine similarity between query and courses
similarities = cosine_similarity(query_embedding, course_embeddings)

# Get index of most similar course
best_match_index = similarities.argmax()

# Display recommendation
print("Student Query:", query)
print("Recommended Course:", courses[best_match_index])

# Scenario: Hospital FAQ Assistant
# A hospital wants to build a chatbot that helps patients quickly find answers to common questions.
# - Problem: Patients ask questions in different ways. For example:
# - “How do I book an appointment?”
# - “What’s the process to schedule a doctor visit?”
# - “Can I see a physician tomorrow?”
# Traditional keyword search might miss these connections.
# - Solution: Convert FAQs and patient queries into embeddings, then measure similarity to find the closest match.

# 👩‍💻 Code in Context

# Hospital FAQ Assistant using Embeddings

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Hospital FAQ knowledge base
faqs = [
    "How can I book an appointment with a doctor?",
    "What are the hospital visiting hours?",
    "How can I pay my medical bill?",
    "Where is the emergency department located?",
    "How do I cancel or reschedule my appointment?"
]

answers = [
    "You can book an appointment through our website or call the hospital reception.",
    "Visiting hours are from 9 AM to 7 PM every day.",
    "Medical bills can be paid online, at the billing counter, or through our mobile app.",
    "The emergency department is located on the ground floor near the main entrance.",
    "You can cancel or reschedule your appointment through the patient portal or by calling reception."
]

# Convert FAQs into embeddings
faq_embeddings = model.encode(faqs)

# Function to find best matching FAQ
def find_best_answer(query):

    # Convert query to embedding
    query_embedding = model.encode([query])

    # Compute cosine similarity
    similarities = cosine_similarity(query_embedding, faq_embeddings)

    # Find best match index
    best_match = similarities.argmax()

    return answers[best_match]


# Example patient questions
patient_query = "How do I schedule a doctor visit?"

response = find_best_answer(patient_query)

print("Patient Question:", patient_query)
print("Chatbot Answer:", response)

#  Scenario: Package Delivery in a City
# Imagine you run a delivery company in a huge city with 100,000 houses. Each house has a
#  unique “address fingerprint” (like the 384‑dimensional vectors in your code).
# Now, when a customer places an order, you need to quickly find the nearest warehouse or
#  delivery hub to their house. Instead of checking every single house one by one (which would
# be very slow), you use smart strategies:

# 🗺️ HNSW (Hierarchical Navigable Small World)
# - Think of it like a layered city map:
# - Top layer = highways (coarse overview).
# - Middle layer = main roads.
# - Bottom layer = all streets and houses.
# - To find the nearest warehouse, you start at the highway level, zoom into the right district,
# then finally navigate down to the exact street.
# - This is what IndexHNSWFlat does: it builds a graph of connections so you can “hop” quickly
# to the right neighborhood.

# 🏘️ IVF (Inverted File Index)
# - Imagine dividing the city into 256 neighborhoods (Voronoi cells).
# - First, figure out which neighborhood the customer’s house belongs to.
# - Then, only search inside that neighborhood instead of the whole city.
# - This is what IndexIVFFlat does: it clusters vectors and searches only in the most relevant
# clusters.
# - nprobe = 10 means you don’t just check one neighborhood, but the 10 most likely ones —
#  balancing speed and accuracy.

# ⚡ In Plain Words
# - HNSW = zooming in layer by layer on a city map.
# - IVF = splitting the city into neighborhoods and searching locally.
# - Both methods help you find the closest match fast without scanning all 100,000 houses.




!pip install faiss-cpu  # Install faiss

import faiss
import numpy as np

d = 384       # embedding dimension
n = 100_000   # number of vectors

# ── HNSW index ──────────────────────────────
index = faiss.IndexHNSWFlat(d, 32)  # M=32 neighbours
index.hnsw.efConstruction = 200     # build quality
index.hnsw.efSearch = 100           # query quality

vectors = np.random.randn(n, d).astype("float32")
faiss.normalize_L2(vectors)         # L2 normalize
index.add(vectors)                  # add all vectors

query = np.random.randn(1, d).astype("float32")
faiss.normalize_L2(query)
D, I = index.search(query, k=10)    # top-10
print("Indices:", I[0])             # [2341, 8712, ...]
print("Distances:", D[0])           # cosine scores

# ── IVF index (faster for large scale) ──────
nlist = 256   # number of Voronoi cells
quantizer = faiss.IndexFlatL2(d)
index_ivf = faiss.IndexIVFFlat(quantizer, d, nlist)
index_ivf.train(vectors)
index_ivf.add(vectors)
index_ivf.nprobe = 10               # cells to search

# Scenario: Student Course Recommendations
# Imagine you’re running an online learning platform. Students type queries like “beginner-friendly Python tutorials”,
# but your catalog has courses titled “Introduction to Programming with Python”.
# Traditional keyword search might miss the match, but embeddings + vector search (Chroma locally or Pinecone in the cloud)
#  can connect them semantically.

# 🧩 Teaching Exercise Flow
# - Documents (Courses)
# - "Python is a high-level programming language"
# - "Machine learning models need training data"
# - "Dogs are loyal and friendly animals"
# - "Cats are independent and curious pets"
# - Embedding Model
# - Converts each course description into a vector (numbers capturing meaning).
# - Indexing
# - Chroma (local): Great for classroom demos, no API key needed.
# - Pinecone (cloud): Scales to billions of items, perfect for production.
# - Query
# - Student asks: “What animals make good companions?”
# - Embedding of query is compared against course embeddings.
# - Results
# - Top matches:
# - Cats are independent and curious pets
# - Dogs are loyal and friendly animals

# Install required libraries
!pip install chromadb sentence-transformers

# Import libraries
import chromadb
from sentence_transformers import SentenceTransformer

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Create Chroma client (local database)
client = chromadb.Client()

# Create collection
collection = client.create_collection(name="course_recommendations")

# Documents (Courses)
documents = [
    "Python is a high-level programming language",
    "Machine learning models need training data",
    "Dogs are loyal and friendly animals",
    "Cats are independent and curious pets"
]

# Add documents to Chroma with embeddings
collection.add(
    documents=documents,
    ids=["1", "2", "3", "4"],
    embeddings=model.encode(documents).tolist()
)

# Student query
query = "What animals make good companions?"

# Convert query to embedding
query_embedding = model.encode([query]).tolist()

# Search for similar documents
results = collection.query(
    query_embeddings=query_embedding,
    n_results=2
)

# Display results
print("Student Query:", query)
print("\nTop Matching Courses / Documents:\n")

for doc in results["documents"][0]:
    print("-", doc)

# OPTION A: Chroma (local, no API key needed)
!pip install chromadb
!pip install sentence-transformers
import chromadb
from sentence_transformers import SentenceTransformer

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Create Chroma client and collection
client = chromadb.Client()  # or chromadb.PersistentClient(path="./db")
#collection = client.create_collection("docs")

# Sample documents
documents = [
    "Python is a high-level programming language",
    "Machine learning models need training data",
    "Dogs are loyal and friendly animals",
    "Cats are independent and curious pets",
]

# Encode documents into embeddings
embeddings = model.encode(documents).tolist()

# Add to Chroma collection
collection.add(
    documents=documents,
    embeddings=embeddings,
    ids=[f"doc{i}" for i in range(len(documents))],
    metadatas=[{"source": "demo", "idx": i} for i in range(len(documents))]
)

# Query with semantic search
query = "What is python?"
q_emb = model.encode([query]).tolist()
results = collection.query(query_embeddings=q_emb, n_results=3)

# Print results
for doc, dist in zip(results["documents"][0], results["distances"][0]):
    print(f"[{dist:.3f}] {doc}")